title: "Grandes UAI 2018"
description: > # this means to ignore newlines until "baseurl:"
  Grandes UAI is a sport championship of 250Kâ‚¬ budget gathering 1200 ENSAM students from May the 10th to the 13th in Chalons-en-Champagne.
baseurl: "/grandesuai2018.github.io" # the subpath of your site, e.g. /blog
url: "https://gaspard-bourgeois.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown


logo: "css/2017_style/img/logo.png"


google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/GUAI2K18/
  - title: github
    url: https://github.com/Gaspard-Bourgeois/grandesuai2018.github.io

# Build settings
markdown: kramdown
permalink: pretty